BASE_HF_COLBERT_MODEL_NAME = "colbert-ir/colbertv2.0"
#INDEX_ROOT_PATH = '.ragindex/colbert/indexes'
INDEX_ROOT_PATH = 'ragdb'
INDEX_NAME = "default"
INDEX_DIR_PATH = f'{INDEX_ROOT_PATH}/{INDEX_NAME}'
DB_FILE_NAME = f'content.sqlite3'
DB_FILE_PATH = f'{INDEX_DIR_PATH}/{DB_FILE_NAME}'
# INDEX_NAME_RAGA = "ragatouille"
# INDEX_PATH_RAGA = f'.ragindex/colbert/indexes/{INDEX_NAME_RAGA}/'
